#!/usr/bin/env bash

direction="$1"

focusedws=$(hyprctl -j monitors | jaq -r '.[] | select(.focused == true) | .activeWorkspace.id')

command="hyprctl dispatch workspace"

if [ "$focusedws" -lt 10 -a "$direction" == "up" ]; then
  eval "$command +1"
elif [ "$focusedws" -gt 1 -a "$direction" == "down" ]; then
  eval "$command -1"
fi
