#!/bin/bash
IFS=$'\n'

windows=($(swaymsg -t get_tree| jq -r 'recurse(.nodes[]?) | recurse(.floating_nodes[]?) | select(.type=="con"), select(.type=="floating_con") | select((.app_id != null) or .name != null) | {id, app_id, name} | .id, .app_id, .name'))

# build the selection string we will pipe to kickoff
options=""
for ((i=0; i<"${#windows[@]}"; i=i+3,lines++)); do
  id="${windows[i]}"
  app_id="${windows[i+1]}"
  name="${windows[i+2]}"

  building_string="$id"
  if [[ $app_id != "null" ]]; then 
    building_string="$building_string : $app_id"
  fi
  if [[ $name != "null" ]]; then 
    building_string="$building_string : $name"
  fi
  options="$options$building_string\n" 
done

if [[ -n $options ]]; then
  echo -e "$options"
  selection=$(echo -e -n "$options" | kickoff --from-stdin --stdout)

  id=$(echo "$selection" | cut -d ":" -f1)
  if [[ -z $id ]]; then
    exit
  fi

  # change focus to selected container and follow focus with cursor when mouse_warping does not solve the issue
  swaymsg "[con_id=$id]" focus && swaymsg seat - cursor move 0 0
  exit
fi
